#! /bin/bash


sum=0
count=$#

if [ $count -lt 1 ]; then
    echo "ERROR: No numbers given. Please give some numbers as command line arguments."
	        exit 1
			        fi

					        while [ -n "$1" ]; do
							            sum=$(expr $sum + $1)
										                shift # Now $1 points to the next number (arg, actually).
														                done

																		                avg=$(echo "scale=4; $sum / $count"|bc)

																						                echo "The average of the $count numbers is: $avg"

